### ISSUE TITLE
Work Checklist

### ISSUE THREAD

**Issue by bluechill** [bluechill/Gendered-Lyrical-Identification#1]
- [x] Mapping of IDs to Song & Artists (@shawn513)
- [x] Mapping of IDs to Genre (@yuanluya)
- [x] Mapping of IDs to lat/long zones using 10º by 10º zones (@nickgrifka)
- [x] Run SVM on all three (@ivanamies)
- [x] Writeup for checkpoint (@nickgrifka & @bluechill)
